### PR TITLE
Fix null location crash

### LINKED ISSUE #105: Trying to respond to at request before interacting with key location database crashes
Stacktrace:
```
FATAL EXCEPTION: main
Process: xyz.whereuat.whereuat, PID: 3101
android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
    at android.database.AbstractCursor.checkPosition(AbstractCursor.java:460)
    at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
    at android.database.AbstractWindowedCursor.getDouble(AbstractWindowedCursor.java:86)
    at xyz.whereuat.whereuat.x.a(Unknown Source)
    at xyz.whereuat.whereuat.ah.onPostExecute(Unknown Source)
```

### PR DESCRIPTION
**Pull request by kangp3**
Closes #105

### CODE REVIEW

File: app/src/main/java/xyz/whereuat/whereuat/MainActivity.java [hunk 1]
```diff
@@ -162,7 +162,9 @@ public void onReceive(final Context context, final Intent intent) {
                 public void onPostExecute(Object result) {
                     Location loc = LocationProviderService.getLocation();
                     Cursor c = (Cursor) result;
-                    KeyLocationUtils.KeyLocation key_loc = KeyLocationUtils.findNearestLoc(c, loc);
+                    KeyLocationUtils.KeyLocation key_loc =
+                            c.getCount() == 0 ? new KeyLocationUtils.KeyLocation(null, 0, 0) :
```
Comment (JuliusAlexanderIV) [inline app/src/main/java/xyz/whereuat/whereuat/MainActivity.java]: why not just use the empty constructor?

**Comment by JuliusAlexanderIV** [comment]
lgtm
